:page-permalink: /about
= About AsciiDocsy

AsciiDocsy is a simple, clean documentation theme designed to work with AsciiDoc markup out of the box.

In addition to typical Jekyll theme features, AsciiDocsy offers numerous advantages for major documentation projects.
When used with LiquiDoc Ops, this theme is pretty incredible.

AsciiDoc Features::

* Semantic elements like:
** admonitions
** code callouts
* Dynamic features such as:
** source transclusion
** variables and conditional flow
* Asciidoctor Stylesheet Factory onboard

Site Architecture::

* Algolia search integration
* Version switchers
* Tabbed/toggled content

Other Features::

* Sassified CSS
* FontAwesome icons
* Syntax highlighting with highlighter.js

== Background

AsciiDocsy has a lineage.
It is based on Google's popular link:https://www.docsy.dev/docs/[Docsy theme for Hugo], via the link:https://github.com/vsoch/docsy-jekyll[Docsy Jekyll port] done by link:{prime_source_www}[VanessaSaurus].

I used to use Tom Johnson's excellent link:https://github.com/tomjoht/documentation-theme-jekyll[Jekyll Documentation Theme], but after several attempts to create a clean, AsciiDoc-friendly fork, I decided that old favorite is just too heavy to work with.
