:page-permalink: /docs/theme/config/api-reference
:page-data-source: _config.yml
:page-liquid:
:page-layout: reference
= Theme Configuration API

[NOTE]
This reference is highly experimental.
I've only spent about 2 hours coding this as an example of a novel domain-specific language (DSL) reference parsed from YAML by Liquid into AsciiDoc for rendering as HTML (or PDF, etc).

Consider this to be rudimentary documentation generated from data structures found in `_config.yml`.
This would be better generated from a _schema_-like version of these data objects, referencing them with metadata about each block of properties in each feature object.
Instead, we are using the objects directly, supplemented by an optional `$docs` objects embedded in the config data structure.

Also, due to object nesting, lots more recursive processing needs to happen.
The truth is, a simple configuration file that can be commented inline and must be edited in place is not great fodder for an API reference, but I wanted to demonstrate it.

But do look at the AsciiDoc and YAML sources (see links to the right icon:right-arrow[]) for this page if you need inspiration for your own complex content.

// Liquid transclusion tag
{% include config-api.asciidoc %}
