:page-permalink: /docs/theme/config/search/algolia
= Algolia Search Integration

A cloud account with Algolia is required to implement Algolia as a cloud-search provider.

[WARNING]
By default, AsciiDocsy's own Algolia application is configured in the repo.
You will be able to generate local content packages for it, or query its live indices, but you will not be able to write (push) to the cloud indices.

The link:https://www.algolia.com/users/sign_up[Algolia signup] is free.
You only start paying when you use certain thresholds of index space or query bandwidth.

AsciiDocsy's implementation of Algolia's Jekyll plugin (link:https://github.com/algolia/jekyll-algolia[source]) (link:https://community.algolia.com/jekyll-algolia/getting-started.html[docs]) and instantsearch form (link:https://community.algolia.com/instantsearch.js/documentation/[docs]).

== Search Settings

The `site.algolia` object, by default defined in `_config.yml`.

.Object: `site.algolia`
[source,yaml]
----
include::_config.yml[tags=algolia]
----

Additionally, each search form on your site needs some more data.
By default the search forms draw this info from objects inside `site.data.theme.search`, such as `search-site` and `search-subject`.
These objects need properties for `show.spot` and `meta.index`.

.Object: `site.data.theme.search.site`
[source,yaml]
----
include::_docs/_data/theme/search.yml[tags=search-site-core]
----

[WARNING]
These settings are only used for _searching_.

[[index-settings]]
== Index Settings

In order to _index_ your site's content, you will need an auxilliary configuration file with the `algolia` object at the root.
This configuration file can be called instead of or in addition to the main Jekyll config.

._docs/_data/configs/search-index-pages.yml
[source,yaml]
----
include::_docs/_data/configs/search-index-pages.yml[]
----

The search is performed by running a `jekyll algolia` operation with your private API key added.

=== ENV Variable

One option is to add your key explicitly to the commandline as an environment variable.

.Example commandline ENV variable option
 ALGOLIA_API_KEY=01d664977165dbf4cded12199738fabf bundle exec jekyll algolia --config _config.yml,_data/configs/jekyll-search-x.yml

=== Stashed File

Alternatively, stash the key as in a file called `_algolia_api_key` (no file extension).

.Entire contents of file `_algolia_option_key`
 01d664977165dbf4cded12199738fabf

[IMPORTANT]
Be sure to add this file to your [.path]`.gitignore` file.

In this case, you may run the following.

.Example commandline with no ENV variable
 bundle exec jekyll algolia --config _config.yml,_data/configs/jekyll-search-x.yml`

[TIP]
To test your indexing process without pushing to Algolia, add [.cmd]`--dry-run` (or simply [.cmd]`-n`)

For full configuration options, refer to the link:https://community.algolia.com/jekyll-algolia/options.html[Jekyll community documentation].
