:page-permalink: /docs/theme/config/versioning/amenders
= DOM Amenders

By far the most open-ended of the superficial version handlers, DOM amenders enable you to manipulate the DOM in one simple way at a time.
Not a wide-open API like jQuery itself, but a simple way to execute a jQuery function on the `change()` event.

Use cases include switching URLs or switching CSS files in the HTML `<head>`.

== Configuring a DOM Amender

To create a straightforward amender, create an entry in `site.features.versioning` and give it a `verb: amend` property.

=== Your Own DOM Amender

AsciiDocsy provides two key components to establish this functionality.
The first is the *formfield elements* populated by an array and defined by other settings, as with other version handlers.

The *selector.html* partial can generate generate either a selectbox or radio buttons.
Pass it an array of scalars to establish the displayed option and the underlying value as one and the same.
Pass an array of dictionary objects bearing `text` and `slug` properties, and it will use these values for the

=== Your Own Amender Function
