:page-permalink: /docs/theme/config/versioning/swaps
:theme: <$tok.theme>
:company: <$tok.company>
:company_url: <$tok.company_url>
:product_vrsn: 1.2.1
:vrsn: <$tok.vrsn>
:page-toggles: user-os
= Configure Content Token Swaps

== Swap Definition

Like other handlers, swaps are defined in the `versioning` data object.
Name a swap object whatever you wish, and then give it the property `verb: swap`.

A swap can take be triggered by either a `select` dropdown or radio `buttons`.

Swaps can have a `dict:` property that establishes default tokens.
They must have an `swap.opts:` property that defines the "`slates`" of tokens.
These slates are what is being chosen during a swap.

[IMPORTANT]
Even though tokens are broken down to separate dicts and slates, _tokens must be unique across all dictionaries_.
At expression time, swaps alter the value of _every_ token bearing that slug.

== Token Expression

To express a token inside AsciiDoc text, use one of the following methods.

If you want to impose the token somewhere other than inline text, you will not want the trappings of the inline semantics syntax.
In this case, use a token formatted like so: `<$tok.token_name>`.
Replace `token_name` with the slug value for your token, and use text to optionally place.

== Examples

=== Patch Version Switcher

We will start with a simple example, and likely the most common implementation: a patch-version switcher.
If the only thing that changes in your docs between patch versions is the patch version itself, use this trick to let users choose the precise product version they are using or installing without changing pages (and without duplicate builds).

On the right-hand sidebar, there is a selectbox labeled [.gui]*Select your patch version:*.

Watch what happens to this text (*<$tok.vrsn>*) when you change the patch version, sourced as [.code.nosub]`<$tok.vrsn>`.

And here is another version ([.tok.vrsn]*0.2.0*) sourced differently ([.code.nosub]`+++[.tok.vrsn]*0.2.0*+++`).


=== Token Slates

Let's say I wanted to distribute a commercial version of AsciiDocsy with its own set of docs.
Obviously these docs would be largely identical to the free version, but they might have some different contents.
And let's say I'm super shady, and in fact I want to sell AsciiDocsy a second time under a completely different name.

First we need to define tokens for swapping.
Let's keep it simple and go with two tokens: `theme` and `company`, which will have different values given different slates (`opts:`).

.Defining a swap dictionary
[source,yaml]
----
features:
  actions:
    versioning:
      ...
      theme-name-tokens:
include::{path_to_jekyll_config}[tags="sample-swap"]
----

The top-level `dict:` [.out]#2# object defines the default dictionary.
Thereafter, slates (items in `opts:` [.out]#3#) can override the defaults as needed using a nested `dict:` [.out]#4# (x2) property of their own.

Here we see the first slate (`foss`) simply uses the default dictionary while each of the next two define overrides.

Now that our tokens are defined, we can start placing them inside our AsciiDoc content.

[source,asciidoc,subs=none]
----
The <$tok.theme> theme, brought to you by <$tok.company> (link:<$tok.company_url>[website]), is really awesome.

The company slogan is <$tok.slogan>.
----

.Renders
====
The <$tok.theme> theme, brought to you by <$tok.company> (link:<$tok.company_url>[website]), is really awesome.

The company slogan is <$tok.slogan>.
====


=== Storing Tokens as AsciiDoc Attributes

Placing AsciiDocsy swap tokens directly in AsciiDoc syntax does not carrt over to non-AsciiDocsy output.
For this and other reasons, the preferred way to handle swap tokens is by defining them with AsciiDoc attributes.

Provide different values to all your  way you can override the token syntax with an explicit value anytime you wish at build-time.

This method easier to manage and looks nicer on the page., as well.

[source,asciidoc,subs=none]
----
The {theme} theme, brought to you by {company} (link:{company_url}[[website]), is really awesome.
----

.Renders
====
The {theme} theme, brought to you by {company} (link:{company_url}[website]), is really awesome.
====

Without storing your tokens as attributes, you are stuck with those tokens in alternative formats that lack frontend manipulation via JavaScript, such as PDF.

== Toggle Piggy-backing

If a swap and a toggle have the same set of options, the swap can piggy-back on the toggle.
This means the toggle will now perform two actions:

. It will _show_ any content bearing the "`role`" class defined for the toggle (while hiding content bearing toggled-off classes).
. It will also swap any tokens for values assigned to the slate that goes with that role/slug.

Let's look at an example.

[source,yaml]
----
  features:
    actions:
      versioning:
        ...
include::{path_to_jekyll_config}[tags="sample-swap-piggyback"]
----

.See the swap in action
====
your OS::
[.os-mac]#MacOS# [.os-nix]#Linux/Unix# [.os-win]#Windows#


something about your technology::
<$tok.your_os>

something about you::
<$tok.you>
====

.Swap source
[source,asciidoc]
----
something about your technology::
<$tok.your_os>

something about you::
<$tok.you>
----
