:page-permalink: /docs/theme/features/frontend
= AsciiDocsy Frontend Overview

== Subject Menu

You are welcome to use the subject menu (`#subject-menu`) for anything you wish, of course, just as you are welcome to hide it.
It is set up as generically as possible, with repurposing in mind.

That said, `#leftbar`-situated nav menu is mainly intended to reference either a simple lists of topics within your subject or complex, nested combinations of links to topics and artifacts for a subject or a set of subjects.

=== Sourcing

The JavaScript and CSS rendering of the subject menu is handled by a jQuery component called link:https://computerwolf.github.io/SlickNav/[SlickNav].
A template (`_includes/subject-menu.html`) parses `_data/manifest.yml` into HTML unordered lists that SlickNav expects.

[NOTE]
The subject menu does not at this time have a way of inferring a menu from the filesystem or even from page metadata (frontmatter).
While this functionality is possible, I have found it clunkier than centralized "`manifest`" data files that coordinate page and topic metadata.

In LiquiDoc Ops, subject menus are generated from more-semantic manifest YAML files that sit inside each subject's _content_-source directory.
These subject manifests organizes topics and establish their metadata, passing it to each page/topic at buildtime but also making it available to the entire build.
During the prebuild procedure, an intermediate Liquid template parses that data into a new YAML file in the format the AsciiDocsy subject menu uses (just as others reformat that subject-manifest data for reuse elsewhere).

== Topic TOC

The topic table-of-contents is generated by Bootstrap's scroolspy component.
The client (browser) renders headers of designated levels into TOC items with anchor links.

It remains in a static position as you scroll the page, tracking your position by highlighting the appropriate item in the TOC.

== Top Navbar

Typically used for sitewide pages or key external links, the `#topnav` menu can accommodate pretty hefty nesting, if needed.

== Page Links

== Banners

== Landing Page
