:page-permalink: /docs/theme/config/versioning/amenders
= DOM Amenders

By far the most open-ended of the superficial version handlers, DOM amenders enable you to manipulate the DOM in one simple way at a time.
Not a wide-open API like jQuery itself, but a simple way to execute a jQuery function on the `change()` event.

Use cases include switching URLs or switching CSS files in the HTML `<head>`.

== Configuring a DOM Amender

To create a straightforward amender, create an entry in `site.features.versioning` and give it a `verb: amend` property.

=== Your Own DOM Amender

AsciiDocsy provides two key components to establish this functionality.
The first is the *formfield elements* populated by an array and defined by other settings, as with other version handlers.

The *version-handler.html* partial can generate generate either a `select` dropdown or radio `buttons`.
Pass it an array of scalars to establish the displayed option and the underlying value as one and the same.
Pass an array of dictionary objects bearing `text` and `slug` properties, and it will use these values for the option _labels_ and _values_, respectively.

=== Your Own Amender Function

To provide your own DOM amender, add a template file (`.html` or `.js`)= to the `_includes/` directory, and register it as the `func.file` value inside your amender block.

.Example custom amender definition
[source,yaml]
----
  versioning:
    ...
    my-amender:
      verb: amend
      form: select
      func:
        file: my-amender.js
      swap:
        data: site.data.my-array
        pick: some-value
----

Your handler will be interpreted by `_includes/versioning-controls.html` and the controller will be generated by `_includes/version-handlers.html`.
